apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: testchat1 
  janus-idp.io/tekton: testchat1
  backstage.io/kubernetes-id: testchat1
  backstage.io/kubernetes-namespace: testns 
  app.kubernetes.io/part-of: testchat1
resources: 
- application-dev.yaml