apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testchat1
  janus-idp.io/tekton: testchat1
  backstage.io/kubernetes-id: testchat1
  backstage.io/kubernetes-namespace: testns 
  app.kubernetes.io/part-of: testchat1
resources: 
- initialize-namespace.yaml
- pvc.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- rhoai/