---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: testchat1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testchat1 
  name: testchat1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi