apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: testchat1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testchat1 
  name: testchat1
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: testchat1 
